# Site settings
title: Trustlines
subtitle: Developer Docs
email: youremailaddress@gmail.com
description: Developer documentation for Trustlines
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1/" # the base hostname & protocol for your site
author: Trustlines Foundation
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Social settings
500px_url:
github_url: https://github.com/trustlines-protocol
twitter_url: https://twitter.com/TrustlinesFound
reddit_url: https://reddit.com/r/Trustlines

# Build settings
markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

highlighter: rouge
