# Site settings

title: Trustlines Developer Docs
subtitle:
email: contact@trustlines.foundation
description: Technical documentation for the Trustlines Network
baseurl: "" # the subpath of your site, e.g. /blog
author: Trustlines Foundation
street_address: St√§dtle 38
city: Vaduz
zip_code: 9490
country: Liechtenstein
tagline: Trustlines Dev Docs | Technical documentation for the Trustlines Network
url: https://dev.trustlines.network
twitter:
  username: TrustlinesFound
  card: summary
  creator: TrustlinesFound
logo: /assets/images/trustlines-mark-logo-blue.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/trustlines-mark-logo-blue.png

# Social settings

github_url: https://github.com/trustlines-protocol
twitter_url: https://twitter.com/TrustlinesFound
reddit_url: https://reddit.com/r/Trustlines
social:
  links:
    - https://twitter.com/TrustlinesFound
    - https://twitter.com/trustlines_app
    - https://reddit.com/r/Trustlines
    - https://github.com/trustlines-protocol
    - https://trustlines.network/
    - https://blog.trustlines.network/
    - https://forum.trustlines.network/
    - https://docs.trustlines.network/
    - https://t.me/trustlines_network
    - https://gitter.im/trustlines/community

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

highlighter: rouge
