# Site settings
title: Trustlines
subtitle: Developer Docs
email: youremailaddress@gmail.com
description: Developer Documentation for Trustlines
baseurl: "" # the subpath of your site, e.g. /blog
author: Trustlines Foundation
street_address: St√§dtle 38
city: Vaduz
zip_code: 9490
country: Liechtenstein
tagline: Trustlines Dev Docs
url: https://docs.trustlines.network/
twitter:
  username: TrustlinesFound
logo: /assets/images/brand/network/png/gradient/TN-Logo-Gradient_1_14.png

# Social settings
500px_url:
github_url: https://github.com/trustlines-protocol
twitter_url: https://twitter.com/TrustlinesFound
reddit_url: https://reddit.com/r/Trustlines
social:
  links:
    - https://twitter.com/TrustlinesFound
    - https://reddit.com/r/Trustlines
    - https://github.com/trustlines-protocol
    - https://trustlines.network/
    - https://blog.trustlines.network/
    - https://forum.trustlines.network/
    - https://docs.trustlines.network/

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

highlighter: rouge
